version: '3.8'

services:
  django:
    build: .
    container_name: django_app
    volumes:
      - .:/app
      - static_volume:/app/static
    expose:
      - "8000"
    command: gunicorn gestion_etudiant.wsgi:application --bind 0.0.0.0:8000
  
  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/static
    ports:
      - "80:80"
    depends_on:
      - django

volumes:
  static_volume:
